name: CI/CD Pipeline with Terraform

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: ./scripts/terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: ./scripts/terraform
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./scripts/terraform
      run: terraform apply -auto-approve

  build:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker images
      run: ./scripts/build-image.sh

    - name: Push Docker images
      run: ./scripts/push-image.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Deploy to Kubernetes
      run: ./scripts/deploy.sh

  delete:
    if: github.event_name == 'delete'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Delete Kubernetes resources
      run: ./scripts/delete.sh
